stages:
  download_inaturalist:
    cmd: uv run python scripts/download_inaturalist_data.py configs/data_config_full.yaml
    deps:
      - scripts/download_inaturalist_data.py
    params:
      - configs/data_config_full.yaml:
          - data.inaturalist
    outs:
      - datasets/inaturalist
  filter_animal:
    cmd: uv run python scripts/filter_data_vlm.py configs/filter_data_vlm_config_animal.yaml
    deps:
      - scripts/filter_data_vlm.py
      - configs/filter_data_vlm_config_animal.yaml
      - datasets/inaturalist
    outs:
      - datasets/filtered_stage1_animal

  filter_flying_bird:
    cmd: uv run python scripts/filter_data_vlm.py configs/filter_data_vlm_config_birds.yaml
    deps:
      - scripts/filter_data_vlm.py
      - configs/filter_data_vlm_config_birds.yaml
      - datasets/filtered_stage1_animal
    outs:
      - datasets/filtered_stage2_birds

  filter_snake:
    cmd: uv run python scripts/filter_data_vlm.py configs/filter_data_vlm_config_snakes.yaml
    deps:
      - scripts/filter_data_vlm.py
      - configs/filter_data_vlm_config_snakes.yaml
      - datasets/filtered_stage1_animal
    outs:
      - datasets/filtered_stage3_snakes
