inaturalist:
  output_path: /home/hmack/Development/rodent_experiments/datasets/full_dataset/raw
  years: []
  first_year: 2000
  last_year: 2026
  quality_grade: research
  species:
    # rodents in europe
    - Rattus norvegicus
    - Rattus rattus
    - Mus musculus
    - Apodemus agrarius
    - Apodemus flavicollis
    - Apodemus sylvaticus
    - Arvicola amphibius
    - Microtus arvalis
    - Clethrionomys glareolus,
    - Microtus agrestis
    - Crocidura leucodon
    - Sorex araneus
    - Sorex minutus
    - Sorex coronatus
    # rodents in sri lanka
    - Suncus murinus
    - Bandicota indica
    - Bandicota bengalensis
    - Mus booduga
    - Vandeleuria oleraceus
    # predators of snakes and rodents (birds, mammals )
    - Vulpes vulpes # red fox
    - Buteo buteo # common buzzard
    - Meles meles # european badger
    - Ciconia ciconia # white stork
    - Ardea cinerea # grey heron
    # snakes
    - Vipera berus # common european adder
    - Coronella austriaca # smooth snake
    - Natrix natrix # grass snake
    - Natrix helvetica # barred grass snake
    # snakes in sri lanka
    - Ptyas mucosa
    - Bungarus caeruleus
    - Naja naja
    - Daboia russelii
    - Coelognathus helena
    # predators from sri lanka
    - Spilornis cheela
    - Varanus bengalensis
    - Centropus sinensis
    - Pavo cristatus
  seed: 42
  max_img_num: 2000
  allowed_licences:
    - "cc-by-nc"
