path_to_image_data: ../datasets/full_dataset/filtered_kept
path_to_labels: ../datasets/full_dataset/speciesnet_box_labels_nopad
dataset_output_path: ../datasets/full_dataset/yolo_detector_training_dataset
class_names:
  - Rattus norvegicus
  - Rattus rattus
  - Mus musculus
  - Apodemus agrarius
  - Apodemus flavicollis
  - Apodemus sylvaticus
  - Arvicola amphibius
  - Microtus arvalis
  - Clethrionomys glareolus
  - Microtus agrestis
  - Micromys minutus
  - Crocidura leucodon
  - Sorex araneus
  - Sorex minutus
  - Sorex coronatus
  - Suncus murinus
  - Bandicota indica
  - Bandicota bengalensis
  - Mus booduga
  - Vandeleuria oleraceus
  - Vulpes vulpes
  - Buteo buteo
  - Meles meles
  - Ciconia ciconia
  - Ardea cinerea
  - Vipera berus
  - Coronella austriaca
  - Natrix natrix
  - Natrix helvetica
  - Ptyas mucosa
  - Bungarus caeruleus
  - Naja naja
  - Daboia russelii
  - Coelognathus helena
  - Spilornis cheela
  - Varanus bengalensis
  - Centropus sinensis
  - Pavo cristatus
  - Canis familiaris
  - Felis catus
  - car
  - empty
labels_to_filter:
  - animal
  - rodent
  - vehicle
train_val_test_split: [0.7, 0.15, 0.15]
rng_seed: 42
confidence_threshold: 0.15
iou_threshold: 0.2
background_image_dir: ../datasets/full_dataset/filtered_kept/empty
background_class_names: [empty]
