metadata_processor_info:
  source_folder: ./datasets/BioTrove/BioTrove
  destination_folder: ./datasets/biotrove-sri-lanka-large/biotrove-sri-lanka-large-filtered
  categories:
  - Rattus norvegicus
  - Rattus rattus
  - Suncus murinus
  - Bandicota indica
  - Bandicota bengalensis
  - Mus booduga
  - Vandeleuria oleracea
  - Mus musculus
  category_type: scientificName
filter_dir: ./datasets/biotrove-sri-lanka-large/sri-lanka_parquet
img_dir: ./datasets/biotrove-sri-lanka-large/imgs
metadata_filter_and_shuffle_info:
  species_count_data: ./datasets/biotrove-sri-lanka-large/biotrove-sri-lanka-large-filtered/combined_sample_counts_per_species.csv
  directory: ./datasets/biotrove-sri-lanka-large
  rare_threshold: 5
  cap_threshold: 100000
  part_size: 500
  rare_dir: ./datasets/biotrove-sri-lanka-large/rare_cases
  cap_filtered_dir_train: ./datasets/biotrove-sri-lanka-large/tmp_cap_filtered
  capped_dir: ./datasets/biotrove-sri-lanka-large/overthecap_cases
  merged_dir: ./datasets/biotrove-sri-lanka-large/processed_metadata
  files_per_chunk: 100
  random_seed: 42
image_download_info:
  processed_metadata_folder: ./datasets/biotrove-sri-lanka-large/processed_metadata
  output_folder: ./datasets/biotrove-sri-lanka-large/img_txt
  start_index: 0
  end_index: null
  concurrent_downloads: 100
img_text_gen_info:
  processed_metadata_folder: ./datasets/biotrove-sri-lanka-large/processed_metadata
  img_folder: ./datasets/biotrove-sri-lanka-large/img_txt
  generate_tar: true
