train_dataset: datasets/stage8_yolo_classifier
model_name: yolo26m-cls.pt
include_macro_f1: true
return_format: dataframe
train_kwargs:
  epochs: 50
  imgsz: 640
  batch: -1
  device: 0
  workers: 10
  patience: 20
  warmup_epochs: 3.0
  optimizer: 'auto'
  project: ./projects/smartrodent_experiments/tuning/yolo_classify_speciesnames
  name:  full_data_classifier_xl_640
  exist_ok: true
  plots: true
  save: true
  val: true
  scale: 0.7
  fliplr: 0.5
  flipud: 0.0
  auto_augment: randaugment # randaugment, augmix, autoaugment, or null
  erasing: 0.1
  # auto_augment: null
  # hsv_h: 0.015
  # hsv_s: 0.4
  # hsv_v: 0.4
export_kwargs:
  format: "onnx"
tune_kwargs:
  name:  full_data_classifier_m_640
  project: ./projects/smartrodent_experiments/tuning/yolo_classify_speciesnames_tune
  epochs: 50
  imgsz: 640
  iterations: 300
  batch: -1
  device: 0
  workers: 10
  patience: 20
  warmup_epochs: 3.0
  optimizer: 'auto'
  plots: true
  save: true
  space:
    lr0:
    - 1.0e-05
    - 0.01
    lrf:
    - 0.01
    - 1.0
    momentum:
    - 0.7
    - 0.98
    weight_decay:
    - 0.0
    - 0.001
    box:
    - 1.0
    - 20.0
    cls:
    - 0.1
    - 4.0
    dfl:
    - 0.4
    - 12.0
    translate:
    - 0.0
    - 0.4
    scale:
    - 0.0
    - 0.8
    fliplr:
    - 0.0
    - 0.5
    mosaic:
    - 0.0
    - 1.0
    close_mosaic:
    - 0
    - 10
    cutmix:
    - 0.0
    - 1.0
    mixup:
    - 0.0
    - 1.0
    bgr:
    - 0.0
    - 1.0
    shear:
    - 0.0
    - 10.0
    perspective:
    - 0.0
    - 0.001
    degrees:
    - 0.0
    - 45.0
    copy_paste:
    - 0.0
    - 1.0