train_dataset: datasets/stage8_yolo_detector
model_name: yolo26x.pt
include_macro_f1: true
return_format: dataframe
mlflow:
  tracking_uri: sqlite:///mlflow.db
  train_experiment_name: smartrodent-yolo-detector-training
  tune_experiment_name: smartrodent-yolo-detector-tuning
train_kwargs:
  epochs: 100
  imgsz: 640
  batch: 24
  device: 0
  workers: 20
  patience: 25
  project: ./projects/smartrodent_experiments/training/yolo_detect
  name: full_data_detector_xl_with_recommended_defaults
  exist_ok: true
  plots: true
  save: true
  val: true
export_kwargs:
  format: "onnx"

tune_kwargs:
  epochs: 30
  iterations: 40
  plots: true
  save: false
  space:
    lr0:
    - 1.0e-05
    - 0.01
    lrf:
    - 0.01
    - 1.0
    momentum:
    - 0.7
    - 0.98
    weight_decay:
    - 0.0
    - 0.001
    box:
    - 1.0
    - 20.0
    cls:
    - 0.1
    - 4.0
    dfl:
    - 0.4
    - 12.0
    translate:
    - 0.0
    - 0.25
    scale:
    - 0.0
    - 0.5
    fliplr:
    - 0.0
    - 0.5
    mosaic:
    - 0.0
    - 1.0
    close_mosaic:
    - 0
    - 10
