train_dataset: /home/hmack/projects/smartrodent_experiments/datasets/full_dataset/yolo_classifier_training_dataset_reduced
model_name: !sweep
  values:
    - yolo26s-cls.pt
    - yolo26m-cls.pt
    - yolo26l-cls.pt
    - yolo26x-cls.pt

include_macro_f1: true
return_format: dataframe
train_kwargs:
  epochs: 50
  imgsz: 640
  batch: -1
  device: 0
  workers: 10
  patience: 20
  warmup_epochs: 3.0
  optimizer: 'auto'
  project: /home/hmack/projects/smartrodent_experiments/training/yolo_classify_reduced
  name: !coupled-sweep
    target: model_name
    values:
      - full_data_classifier_s_640
      - full_data_classifier_m_640
      - full_data_classifier_l_640
      - full_data_classifier_xl_640
  exist_ok: true
  plots: true
  save: true
  val: true
export_kwargs:
  format: "onnx"
tune_kwargs:
  epochs: 30
  iterations: 40
  plots: true
  save: false
  space:
    lr0:
    - 1.0e-05
    - 0.01
    lrf:
    - 0.01
    - 1.0
    momentum:
    - 0.7
    - 0.98
    weight_decay:
    - 0.0
    - 0.001
    box:
    - 1.0
    - 20.0
    cls:
    - 0.1
    - 4.0
    dfl:
    - 0.4
    - 12.0
    translate:
    - 0.0
    - 0.25
    scale:
    - 0.0
    - 0.5
    fliplr:
    - 0.0
    - 0.5
    mosaic:
    - 0.0
    - 1.0
    close_mosaic:
    - 0
    - 10
